/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as LangRouteImport } from "./routes/$lang";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as LangIndexRouteImport } from "./routes/$lang.index";
import { Route as LangLoginRouteImport } from "./routes/$lang.login";
import { Route as LangGuideRouteImport } from "./routes/$lang.guide";

const LangRoute = LangRouteImport.update({
  id: "/$lang",
  path: "/$lang",
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const LangIndexRoute = LangIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => LangRoute,
} as any);
const LangLoginRoute = LangLoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => LangRoute,
} as any);
const LangGuideRoute = LangGuideRouteImport.update({
  id: "/guide",
  path: "/guide",
  getParentRoute: () => LangRoute,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/$lang": typeof LangRouteWithChildren;
  "/$lang/guide": typeof LangGuideRoute;
  "/$lang/login": typeof LangLoginRoute;
  "/$lang/": typeof LangIndexRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/$lang/guide": typeof LangGuideRoute;
  "/$lang/login": typeof LangLoginRoute;
  "/$lang": typeof LangIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/$lang": typeof LangRouteWithChildren;
  "/$lang/guide": typeof LangGuideRoute;
  "/$lang/login": typeof LangLoginRoute;
  "/$lang/": typeof LangIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: "/" | "/$lang" | "/$lang/guide" | "/$lang/login" | "/$lang/";
  fileRoutesByTo: FileRoutesByTo;
  to: "/" | "/$lang/guide" | "/$lang/login" | "/$lang";
  id: "__root__" | "/" | "/$lang" | "/$lang/guide" | "/$lang/login" | "/$lang/";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  LangRoute: typeof LangRouteWithChildren;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/$lang": {
      id: "/$lang";
      path: "/$lang";
      fullPath: "/$lang";
      preLoaderRoute: typeof LangRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/$lang/": {
      id: "/$lang/";
      path: "/";
      fullPath: "/$lang/";
      preLoaderRoute: typeof LangIndexRouteImport;
      parentRoute: typeof LangRoute;
    };
    "/$lang/login": {
      id: "/$lang/login";
      path: "/login";
      fullPath: "/$lang/login";
      preLoaderRoute: typeof LangLoginRouteImport;
      parentRoute: typeof LangRoute;
    };
    "/$lang/guide": {
      id: "/$lang/guide";
      path: "/guide";
      fullPath: "/$lang/guide";
      preLoaderRoute: typeof LangGuideRouteImport;
      parentRoute: typeof LangRoute;
    };
  }
}

interface LangRouteChildren {
  LangGuideRoute: typeof LangGuideRoute;
  LangLoginRoute: typeof LangLoginRoute;
  LangIndexRoute: typeof LangIndexRoute;
}

const LangRouteChildren: LangRouteChildren = {
  LangGuideRoute: LangGuideRoute,
  LangLoginRoute: LangLoginRoute,
  LangIndexRoute: LangIndexRoute,
};

const LangRouteWithChildren = LangRoute._addFileChildren(LangRouteChildren);

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LangRoute: LangRouteWithChildren,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

import type { getRouter } from "./router.tsx";
import type { createStart } from "@tanstack/react-start";
declare module "@tanstack/react-start" {
  interface Register {
    ssr: true;
    router: Awaited<ReturnType<typeof getRouter>>;
  }
}
