// generated by @better-translate/cli
export const ar = {
  codeDemo: {
    description: "نفس الإعدادات تعمل بشكل متطابق سواء كنت في Next.js أو Astro أو React أو Node عادي.",
    title: "واجهة برمجية واحدة. كل بيئة",
  },
  features: {
    description: "نفس الإعداد، نفس الواجهة البرمجية، نفس التجربة، بغض النظر عن بيئة TypeScript التي تستخدمها.",
    items: {
      autocomplete: {
        description: "محررك يعرف كل مفتاح في كائن الرسائل الخاص بك. لا مزيد من التخمين لأن `t(\"home.` يبدأ الإكمال على الفور.",
        title: "الإكمال التلقائي في كل مكان",
      },
      frameworkAgnostic: {
        description: "اكتب إعدادات الترجمة مرة واحدة. تعمل بشكل متطابق في Next.js و Astro و React و TanStack Router و Node عادي. قم بتبديل البيئات، احتفظ بإعدادك.",
        title: "نفس الإعدادات، كل بيئة",
      },
      localeSwitching: {
        description: "قم بتبديل اللغات في وقت التشغيل بدون إعادة تحميل الصفحة. تجاوزات لكل استدعاء تسمح لك بعرض أي لغة عند الطلب.",
        title: "تبديل اللغة",
      },
      typeSafe: {
        description: "استدلال TypeScript كامل على مفاتيح الترجمة ومتغيرات الاستيفاء. الأخطاء الإملائية والمفاتيح المفقودة تصبح أخطاء في الترجمة.",
        title: "آمن من حيث النوع بشكل افتراضي",
      },
    },
    title: "نفس الإعداد. كل بيئة",
  },
  footer: {
    docs: "التوثيق",
    github: "GitHub",
    legal: "رخصة MIT · مبني باستخدام TypeScript",
    npm: "npm",
    sponsor: "ادعم المشروع",
  },
  frameworks: {
    description: "إعدادات الترجمة الخاصة بك تعمل بنفس الطريقة في كل بيئة TypeScript. محولات أصلية، واجهة برمجية متطابقة.",
    heroDescription: "قم بتبديل الأطر العمل بدون إعادة كتابة إعداد i18n الخاص بك",
    heroTitle: "نفس الإعدادات في كل مكان",
    items: {
      astro: {
        description: "مساعدات محدودة النطاق والمجموعات المحلية من محتوى Astro لـ .md و .mdx.",
      },
      bun: {
        description: "دعم وقت تشغيل Bun الأصلي بدون إعداد إضافي.",
      },
      nextjs: {
        description: "مكونات الخادم و App Router ومساعدات اللغة الموجهة للمسار.",
      },
      nodejs: {
        description: "نواة بدون تبعيات للبرامج النصية والخوادم والمهام الخلفية.",
      },
      react: {
        description: "السياق والخطافات وعرض العميل الذي يدرك اللغة لتطبيقات React.",
      },
      tanstack: {
        description: "دعم التوجيه الآمن من حيث النوع لمشاريع TanStack Router، بما في ذلك تطبيقات TanStack Start.",
      },
      typescript: {
        description: "أنواع قوية والإكمال التلقائي والتعليقات في وقت الترجمة من رسائلك.",
      },
    },
    title: "إطار العمل الخاص بك، اختيارك",
  },
  header: {
    changelog: "سجل التغييرات",
    cli: "CLI",
    closeMenu: "إغلاق القائمة",
    docs: "التوثيق",
    github: "GitHub",
    language: "اللغة",
    languageSwitcher: "تبديل اللغة",
    openMenu: "فتح القائمة",
    sponsor: "ادعم المشروع",
  },
  hero: {
    badge: "نفس الإعدادات. كل بيئة TypeScript",
    description: "نفس الإعدادات. نفس الواجهة البرمجية. تعمل في Next.js و Astro و React و TanStack Router و Node عادي. بدون إعادة كتابة.",
    primaryCta: "عرض التوثيق",
    secondaryCta: "عرض على GitHub",
    sponsorCta: "ادعم المشروع",
    title: "إعداد i18n واحد لأي مشروع TypeScript",
  },
  thanksForSupport: {
    title: "شكراً لدعمك!",
    description: "رعايتك تعني الكثير. تساعد في إبقاء better-translate مفتوح المصدر، مُصاناً، ومجانياً للجميع.",
    impact1: "يُتيح الاستمرار في التطوير والصيانة",
    impact2: "يبقي المكتبة مجانية ومفتوحة المصدر",
    impact3: "يموّل محولات أطر عمل جديدة وميزات إضافية",
    backHome: "العودة إلى الرئيسية",
    viewGithub: "عرض على GitHub",
  },
  docs: {
    copyMarkdown: "نسخ markdown",
    copiedMarkdown: "تم النسخ",
    header: {
      home: "الرئيسية",
      github: "GitHub",
    },
    sidebar: {
      rtl: "RTL",
      adapters: "المحولات",
      astro: "Astro",
      changelog: "سجل التغييرات",
      cli: "CLI",
      core: "النواة",
      expo: "Expo",
      gettingStarted: "البدء",
      installation: "التثبيت",
      introduction: "المقدمة",
      mission: "المهمة",
      mdAndMdx: "MD & MDX",
      nextjs: "Next.js",
      react: "React",
      skills: "المهارات",
      tanstackStart: "TanStack Router",
    },
  },
} as const;

export default ar;
