// generated by @better-translate/cli
export const ar = {
  codeDemo: {
    description:
      "أنشئ ملفات الإعدادات المحلية باستخدام نفس CLI سواء كنت تستخدم AI Gateway أو نماذج Ollama المحلية.",
    title: "مستضافة أو محلية. نفس CLI",
  },
  features: {
    description:
      "نفس الإعداد، نفس API، نفس التجربة، بغض النظر عن بيئة TypeScript التي تستخدمها.",
    items: {
      autocomplete: {
        description:
          'محررك يعرف كل مفتاح في كائن رسائلك. لا مزيد من التخمين لأن `t("home.` يبدأ الإكمال فوراً.',
        title: "الإكمال التلقائي في كل مكان",
      },
      frameworkAgnostic: {
        description:
          "اكتب إعداد الترجمة مرة واحدة. يعمل بنفس الطريقة في Next.js وAstro وReact وTanStack Router وNode العادي. بدّل البيئات، احتفظ بإعدادك.",
        title: "نفس الإعداد، كل بيئة",
      },
      localeSwitching: {
        description:
          "بدّل اللغات أثناء التشغيل دون إعادة تحميل الصفحة. التجاوزات لكل استدعاء تتيح لك عرض أي لغة عند الطلب.",
        title: "تبديل اللغة",
      },
      typeSafe: {
        description:
          "استدلال TypeScript كامل لمفاتيح الترجمة ومتغيرات الاستيفاء. الأخطاء المطبعية والمفاتيح المفقودة تصبح أخطاء ترجمة.",
        title: "آمن النوع افتراضياً",
      },
    },
    title: "نفس الإعداد. كل بيئة",
  },
  footer: {
    docs: "التوثيق",
    github: "GitHub",
    legal: "ترخيص MIT · مبني بـ TypeScript",
    npm: "npm",
    sponsor: "الرعاية",
  },
  frameworks: {
    description:
      "إعداد الترجمة الخاص بك يعمل بنفس الطريقة في كل بيئة TypeScript. محولات أصلية، API متطابق.",
    heroDescription: "بدّل أطر العمل دون إعادة كتابة إعداد i18n الخاص بك",
    heroTitle: "نفس الإعداد في كل مكان",
    items: {
      astro: {
        description:
          "مساعدات محددة بالطلب ومجموعات محتوى Astro المحلية لـ .md و.mdx.",
      },
      bun: {
        description: "دعم أصلي لوقت تشغيل Bun بدون إعداد إضافي.",
      },
      nextjs: {
        description: "مكونات الخادم وApp Router ومساعدي اللغة المدركين للمسار.",
      },
      nodejs: {
        description: "الأساس بدون تبعيات للنصوص والخوادم والمهام الخلفية.",
      },
      react: {
        description:
          "السياق والخطافات والعرض العميل المدرك للغة لتطبيقات React.",
      },
      tanstack: {
        description:
          "دعم التوجيه الآمن النوعياً لمشاريع TanStack Router، بما في ذلك تطبيقات TanStack Start.",
      },
      typescript: {
        description:
          "أنواع قوية، إكمال تلقائي، وردود فعل وقت الترجمة من رسائلك.",
      },
    },
    title: "إطار عملك، اختيارك",
  },
  header: {
    changelog: "سجل التغييرات",
    cli: "CLI",
    closeMenu: "إغلاق القائمة",
    docs: "التوثيق",
    github: "GitHub",
    language: "اللغة",
    languageSwitcher: "تبديل اللغة",
    openMenu: "فتح القائمة",
  },
  hero: {
    badges: {
      sameConfig: "نفس الإعداد. نماذج مستضافة أو محلية",
      typeSafe: "ترجمات آمنة النوع افتراضياً",
      oneSetup: "إعداد واحد لـ Next.js وAstro وReact والمزيد",
      autocomplete: "إكمال تلقائي لكل مفتاح ترجمة",
      localeSwitching: "تبديل اللغة بدون إعادة تحميل الصفحة",
      generateLocales: "أنشئ لغات باستخدام AI أو Ollama المحلي",
    },
    description:
      "اضبط مرة واحدة. ترجم في كل مكان. i18n آمن من حيث الأنواع لـ Next.js وAstro وReact وTanStack Router وأي بيئة TypeScript.",
    primaryCta: "عرض التوثيق",
    secondaryCta: "عرض على GitHub",
    sponsorCta: "رعاية المشروع",
    title: "إعداد i18n واحد لأي مشروع TypeScript",
  },
  thanksForSupport: {
    title: "شكراً لدعمك!",
    description:
      "رعايتك تعني الكثير. إنها تساعد في الحفاظ على better-translate مفتوح المصدر، ومتين، ومجاني للجميع.",
    impact1: "تتيح التطوير والصيانة المستمرة",
    impact2: "تحافظ على المكتبة مجانية ومفتوحة المصدر",
    impact3: "تموّل محولات أطر عمل جديدة وميزات",
    backHome: "العودة للرئيسية",
    viewGithub: "عرض على GitHub",
  },
  docs: {
    copyMarkdown: "نسخ markdown",
    copiedMarkdown: "تم النسخ",
    header: {
      home: "الرئيسية",
      github: "GitHub",
    },
    sidebar: {
      rtl: "RTL",
      adapters: "المحولات",
      astro: "Astro",
      changelog: "سجل التغييرات",
      cli: "CLI",
      core: "الأساس",
      expo: "Expo",
      gettingStarted: "البدء",
      installation: "التثبيت",
      introduction: "المقدمة",
      mission: "المهمة",
      mdAndMdx: "MD & MDX",
      nextjs: "Next.js",
      react: "React",
      skills: "المهارات",
      tanstackStart: "TanStack Router",
    },
  },
} as const;

export default ar;
