// generated by @better-translate/cli
export const es = {
  codeDemo: {
    description: "La misma configuración funciona de forma idéntica ya sea que estés en Next.js, Astro, React o Node simple.",
    title: "Una API. Cada entorno",
  },
  features: {
    description: "La misma configuración, la misma API, la misma experiencia, sin importar en qué entorno de TypeScript estés.",
    items: {
      autocomplete: {
        description: "Tu editor conoce cada clave en tu objeto de mensajes. Sin más adivinanzas porque `t(\"home.` comienza a completarse al instante.",
        title: "Autocompletado en Todas Partes",
      },
      frameworkAgnostic: {
        description: "Escribe tu configuración de traducción una vez. Funciona de forma idéntica en Next.js, Astro, React, TanStack Router y Node simple. Cambia de entorno, mantén tu configuración.",
        title: "Misma Configuración, Cada Entorno",
      },
      localeSwitching: {
        description: "Cambia de idioma en tiempo de ejecución sin recargar la página. Las anulaciones por llamada te permiten renderizar cualquier idioma bajo demanda.",
        title: "Cambio de Idioma",
      },
      typeSafe: {
        description: "Inferencia completa de TypeScript en claves de traducción y variables de interpolación. Los errores tipográficos y las claves faltantes se convierten en errores de compilación.",
        title: "Seguro de Tipos por Defecto",
      },
    },
    title: "Misma configuración. Cada entorno",
  },
  footer: {
    docs: "Documentación",
    github: "GitHub",
    legal: "Licencia MIT · construido con TypeScript",
    npm: "npm",
    sponsor: "Patrocinar",
  },
  frameworks: {
    description: "Tu configuración de traducción funciona de la misma manera en cada entorno de TypeScript. Adaptadores nativos, API idéntica.",
    heroDescription: "Cambia de framework sin reescribir tu configuración i18n",
    heroTitle: "Misma configuración en todas partes",
    items: {
      astro: {
        description: "Ayudantes con alcance de solicitud y colecciones de contenido de Astro localizadas para .md y .mdx.",
      },
      bun: {
        description: "Soporte nativo del tiempo de ejecución de Bun sin configuración adicional.",
      },
      nextjs: {
        description: "Componentes de servidor, App Router y ayudantes de idioma conscientes de rutas.",
      },
      nodejs: {
        description: "Núcleo sin dependencias para scripts, servidores y trabajos en segundo plano.",
      },
      react: {
        description: "Contexto, hooks y renderizado del cliente consciente del idioma para aplicaciones React.",
      },
      expo: {
        description: "Los mismos hooks y contexto de React para apps de Expo y React Native. Sin paquete nativo separado.",
      },
      tanstack: {
        description: "Soporte de enrutamiento seguro de tipos para proyectos de TanStack Router, incluidas aplicaciones de TanStack Start.",
      },
      typescript: {
        description: "Tipos sólidos, autocompletado y retroalimentación en tiempo de compilación desde tus mensajes.",
      },
    },
    title: "Tu framework, tu elección",
  },
  header: {
    changelog: "Registro de cambios",
    cli: "CLI",
    closeMenu: "Cerrar menú",
    docs: "Documentación",
    github: "GitHub",
    language: "Idioma",
    languageSwitcher: "Cambiar idioma",
    openMenu: "Abrir menú",
    sponsor: "Patrocinar",
  },
  hero: {
    badge: "Misma configuración. Cada entorno de TypeScript",
    description: "Misma configuración. Misma API. Funciona en Next.js, Astro, React, TanStack Router y Node simple. Sin reescrituras.",
    primaryCta: "Ver documentación",
    secondaryCta: "Ver en GitHub",
    sponsorCta: "Patrocinar el proyecto",
    title: "Una configuración i18n para cualquier proyecto de TypeScript",
  },
  thanksForSupport: {
    title: "¡Gracias por tu apoyo!",
    description: "Tu patrocinio significa mucho. Ayuda a mantener better-translate como código abierto, mantenido y gratuito para todos.",
    impact1: "Permite el desarrollo y mantenimiento continuo",
    impact2: "Mantiene la librería gratuita y de código abierto",
    impact3: "Financia nuevos adaptadores de frameworks y funcionalidades",
    backHome: "Volver al inicio",
    viewGithub: "Ver en GitHub",
  },
  docs: {
    copyMarkdown: "Copiar markdown",
    copiedMarkdown: "Copiado",
    header: {
      home: "Inicio",
      github: "GitHub",
    },
    sidebar: {
      rtl: "RTL",
      adapters: "Adaptadores",
      astro: "Astro",
      changelog: "Registro de cambios",
      cli: "CLI",
      core: "Core",
      expo: "Expo",
      gettingStarted: "Primeros Pasos",
      installation: "Instalación",
      introduction: "Introducción",
      mission: "Misión",
      mdAndMdx: "MD & MDX",
      nextjs: "Next.js",
      react: "React",
      skills: "Habilidades",
      tanstackStart: "TanStack Router",
    },
  },
} as const;

export default es;
