// generated by @better-translate/cli
export const es = {
  codeDemo: {
    description:
      "Genera archivos de localización con el mismo CLI, ya sea que uses AI Gateway o modelos locales de Ollama.",
    title: "Hosteado o local. Mismo CLI",
  },
  features: {
    description:
      "La misma configuración, la misma API, la misma experiencia, sin importar en qué entorno TypeScript te encuentres.",
    items: {
      autocomplete: {
        description:
          'Tu editor conoce cada clave en tu objeto de mensajes. No más adivinar porque `t("home.` comienza a completarse al instante.',
        title: "Autocompletado en Todas Partes",
      },
      frameworkAgnostic: {
        description:
          "Escribe tu configuración de traducción una vez. Funciona idénticamente en Next.js, Astro, React, TanStack Router y Node puro. Cambia de entorno, conserva tu configuración.",
        title: "Misma Config, Cada Entorno",
      },
      localeSwitching: {
        description:
          "Cambia de localización en tiempo de ejecución sin recargar la página. Las anulaciones por llamada te permiten renderizar cualquier localización bajo demanda.",
        title: "Cambio de Localización",
      },
      typeSafe: {
        description:
          "Inferencia completa de TypeScript en claves de traducción y variables de interpolación. Errores tipográficos y claves faltantes se convierten en errores de compilación.",
        title: "Type-Safe por Defecto",
      },
    },
    title: "Misma configuración. Cada entorno",
  },
  footer: {
    docs: "Docs",
    github: "GitHub",
    legal: "MIT License · construido con TypeScript",
    npm: "npm",
    sponsor: "Sponsor",
  },
  frameworks: {
    description:
      "Tu configuración de traducción funciona de la misma manera en cada entorno TypeScript. Adaptadores nativos, API idéntica.",
    heroDescription: "Cambia de framework sin reescribir tu configuración i18n",
    heroTitle: "Misma config en todas partes",
    items: {
      astro: {
        description:
          "Helpers con alcance de petición y colecciones de contenido localizadas de Astro para .md y .mdx.",
      },
      bun: {
        description:
          "Soporte nativo del runtime de Bun sin configuración extra.",
      },
      nextjs: {
        description:
          "Componentes de servidor, App Router y helpers de localización conscientes de rutas.",
      },
      nodejs: {
        description:
          "Núcleo sin dependencias para scripts, servidores y trabajos en segundo plano.",
      },
      react: {
        description:
          "Contexto, hooks y renderizado del cliente consciente de localización para apps React.",
      },
      tanstack: {
        description:
          "Soporte de routing type-safe para proyectos de TanStack Router, incluyendo apps de TanStack Start.",
      },
      typescript: {
        description:
          "Tipos fuertes, autocompletado y feedback en tiempo de compilación de tus mensajes.",
      },
    },
    title: "Tu framework, tu elección",
  },
  header: {
    changelog: "Changelog",
    cli: "CLI",
    closeMenu: "Cerrar menú",
    docs: "Docs",
    github: "GitHub",
    language: "Idioma",
    languageSwitcher: "Cambiar idioma",
    openMenu: "Abrir menú",
    sponsor: "Sponsor",
  },
  hero: {
    badges: {
      sameConfig: "Misma config. Modelos hosteados o locales",
      typeSafe: "Traducciones con type-safe por defecto",
      oneSetup: "Una configuración para Next.js, Astro, React y más",
      autocomplete: "Autocompletado en cada clave de traducción",
      localeSwitching: "Cambio de idioma sin recargar la página",
      generateLocales: "Genera locales con IA o Ollama local",
    },
    description:
      "Configura una vez. Traduce en todas partes. i18n con tipos seguros para Next.js, Astro, React, TanStack Router y cualquier entorno TypeScript.",
    primaryCta: "Ver docs",
    secondaryCta: "Ver en GitHub",
    sponsorCta: "Sponsorizar el proyecto",
    title: "Una configuración i18n para cualquier proyecto TypeScript",
  },
  thanksForSupport: {
    title: "¡Gracias por tu apoyo!",
    description:
      "Tu sponsor significa mucho. Ayuda a mantener better-translate open source, mantenido y gratis para todos.",
    impact1: "Permite el desarrollo y mantenimiento continuo",
    impact2: "Mantiene la librería gratis y open source",
    impact3: "Financia nuevos adaptadores de framework y funcionalidades",
    backHome: "Volver al inicio",
    viewGithub: "Ver en GitHub",
  },
  docs: {
    copyMarkdown: "Copiar markdown",
    copiedMarkdown: "Copiado",
    header: {
      home: "Inicio",
      github: "GitHub",
    },
    sidebar: {
      rtl: "RTL",
      adapters: "Adaptadores",
      astro: "Astro",
      changelog: "Changelog",
      cli: "CLI",
      core: "Core",
      expo: "Expo",
      gettingStarted: "Empezar",
      installation: "Instalación",
      introduction: "Introducción",
      mission: "Misión",
      mdAndMdx: "MD y MDX",
      nextjs: "Next.js",
      react: "React",
      skills: "Habilidades",
      tanstackStart: "TanStack Router",
    },
  },
} as const;

export default es;
