// generated by @better-translate/cli
export const ja = {
  codeDemo: {
    description: "Next.js、Astro、React、またはプレーンNodeのいずれにいても、同じ設定が同じように機能します。",
    title: "1つのAPI。すべての環境",
  },
  features: {
    description: "どのTypeScript環境にいても、同じセットアップ、同じAPI、同じエクスペリエンス。",
    items: {
      autocomplete: {
        description: "エディタはメッセージオブジェクトのすべてのキーを認識します。`t(\"home.`と入力すると即座に補完が始まるため、推測する必要はありません。",
        title: "どこでもオートコンプリート",
      },
      frameworkAgnostic: {
        description: "翻訳設定を1回書きます。Next.js、Astro、React、TanStack Router、プレーンNodeで同じように機能します。環境を切り替えても、セットアップは変わりません。",
        title: "同じ設定、すべての環境",
      },
      localeSwitching: {
        description: "ページをリロードせずに実行時にロケールを切り替えます。呼び出しごとのオーバーライドにより、任意のロケールをオンデマンドでレンダリングできます。",
        title: "ロケール切り替え",
      },
      typeSafe: {
        description: "翻訳キーと補間変数に対する完全なTypeScript推論。タイプミスと欠落キーはコンパイルエラーになります。",
        title: "デフォルトでタイプセーフ",
      },
    },
    title: "同じセットアップ。すべての環境",
  },
  footer: {
    docs: "ドキュメント",
    github: "GitHub",
    legal: "MITライセンス · TypeScriptで構築",
    npm: "npm",
    sponsor: "スポンサー",
  },
  frameworks: {
    description: "翻訳設定はすべてのTypeScript環境で同じように機能します。ネイティブアダプタ、同じAPI。",
    heroDescription: "i18nセットアップを書き直さずにフレームワークを切り替える",
    heroTitle: "どこでも同じ設定",
    items: {
      astro: {
        description: "リクエストスコープのヘルパーと.mdおよび.mdxのローカライズされたAstroコンテンツコレクション。",
      },
      bun: {
        description: "追加のセットアップなしでネイティブBunランタイムをサポート。",
      },
      nextjs: {
        description: "サーバーコンポーネント、App Router、およびルート対応のロケールヘルパー。",
      },
      nodejs: {
        description: "スクリプト、サーバー、バックグラウンドジョブ用の依存関係ゼロのコア。",
      },
      react: {
        description: "Context、フック、およびReactアプリ用のロケール対応クライアントレンダリング。",
      },
      tanstack: {
        description: "TanStack Routerプロジェクト（TanStack Startアプリを含む）のタイプセーフなルーティングサポート。",
      },
      typescript: {
        description: "メッセージから得られる強力な型、オートコンプリート、およびコンパイル時フィードバック。",
      },
    },
    title: "あなたのフレームワーク、あなたの選択",
  },
  header: {
    changelog: "変更履歴",
    cli: "CLI",
    closeMenu: "メニューを閉じる",
    docs: "ドキュメント",
    github: "GitHub",
    language: "言語",
    languageSwitcher: "言語を切り替える",
    openMenu: "メニューを開く",
    sponsor: "スポンサー",
  },
  hero: {
    badge: "同じ設定。すべてのTypeScript環境",
    description: "同じ設定。同じAPI。Next.js、Astro、React、TanStack Router、プレーンNodeで機能します。書き直しなし。",
    primaryCta: "ドキュメントを表示",
    secondaryCta: "GitHubで表示",
    sponsorCta: "プロジェクトを支援する",
    title: "任意のTypeScriptプロジェクト用の1つのi18nセットアップ",
  },
  thanksForSupport: {
    title: "ご支援ありがとうございます！",
    description: "あなたのスポンサーシップはとても重要です。better-translateをオープンソースで維持し、誰もが無料で使えるよう支えてくれています。",
    impact1: "継続的な開発とメンテナンスを可能にする",
    impact2: "ライブラリを無料かつオープンソースに保つ",
    impact3: "新しいフレームワークアダプタと機能の開発を支援する",
    backHome: "ホームに戻る",
    viewGithub: "GitHubで表示",
  },
  docs: {
    copyMarkdown: "マークダウンをコピー",
    copiedMarkdown: "コピーしました",
    header: {
      home: "ホーム",
      github: "GitHub",
    },
    sidebar: {
      rtl: "RTL",
      adapters: "アダプタ",
      astro: "Astro",
      changelog: "変更履歴",
      cli: "CLI",
      core: "コア",
      expo: "Expo",
      gettingStarted: "はじめに",
      installation: "インストール",
      introduction: "はじめに",
      mission: "ミッション",
      mdAndMdx: "MD & MDX",
      nextjs: "Next.js",
      react: "React",
      skills: "スキル",
      tanstackStart: "TanStack Router",
    },
  },
} as const;

export default ja;
