// generated by @better-translate/cli
export const ja = {
  codeDemo: {
    description:
      "AI Gatewayを使用する場合も、ローカルのOllamaモデルを使用する場合も、同じCLIでロケールファイルを生成できます。",
    title: "ホスト型またはローカル。同じCLI",
  },
  features: {
    description:
      "どのTypeScript環境でも、同じセットアップ、同じAPI、同じ体験が得られます。",
    items: {
      autocomplete: {
        description:
          'エディタはmessagesオブジェクトのすべてのキーを認識します。`t("home.`と入力すれば即座に補完が開始されるため、推測する必要がありません。',
        title: "どこでもオートコンプリート",
      },
      frameworkAgnostic: {
        description:
          "翻訳設定を一度記述すれば、Next.js、Astro、React、TanStack Router、そしてプレーンなNodeで同じように動作します。環境を切り替えても、設定はそのままです。",
        title: "同じ設定、あらゆる環境",
      },
      localeSwitching: {
        description:
          "ページの再読み込みなしで、実行時にロケールを切り替えられます。呼び出しごとの上書きにより、必要に応じて任意のロケールをレンダリングできます。",
        title: "ロケール切り替え",
      },
      typeSafe: {
        description:
          "翻訳キーと補間変数の完全なTypeScript推論。タイプミスや不足キーはコンパイルエラーになります。",
        title: "デフォルトで型安全",
      },
    },
    title: "同じセットアップ。あらゆる環境",
  },
  footer: {
    docs: "ドキュメント",
    github: "GitHub",
    legal: "MITライセンス · TypeScriptで構築",
    npm: "npm",
    sponsor: "スポンサー",
  },
  frameworks: {
    description:
      "あなたの翻訳設定は、あらゆるTypeScript環境で同じように動作します。ネイティブアダプター、同一のAPI。",
    heroDescription:
      "i18n設定を書き換えることなくフレームワークを切り替えられます",
    heroTitle: "どこでも同じ設定",
    items: {
      astro: {
        description:
          "リクエストスコープのヘルパーと、.mdおよび.mdx用のローカライズされたAstroコンテンツコレクション。",
      },
      bun: {
        description: "追加設定なしのネイティブBunランタイム対応。",
      },
      nextjs: {
        description:
          "サーバーコンポーネント、App Router、およびルート認識型ロケールヘルパー。",
      },
      nodejs: {
        description:
          "スクリプト、サーバー、バックグラウンドジョブ向けのゼロ依存コア。",
      },
      react: {
        description:
          "Context、フック、およびReactアプリ向けのロケール認識クライアントレンダリング。",
      },
      tanstack: {
        description:
          "TanStack Startアプリを含むTanStack Routerプロジェクト向けの型安全ルーティング対応。",
      },
      typescript: {
        description:
          "messagesから得られる強力な型、オートコンプリート、およびコンパイル時フィードバック。",
      },
    },
    title: "あなたのフレームワーク、あなたの選択",
  },
  header: {
    changelog: "変更履歴",
    cli: "CLI",
    closeMenu: "メニューを閉じる",
    docs: "ドキュメント",
    github: "GitHub",
    language: "言語",
    languageSwitcher: "言語を切り替え",
    openMenu: "メニューを開く",
  },
  hero: {
    badges: {
      sameConfig: "同じ設定。ホスト型またはローカルモデル",
      typeSafe: "デフォルトで型安全な翻訳",
      oneSetup: "Next.js、Astro、Reactなど向けの1つの設定",
      autocomplete: "すべての翻訳キーでオートコンプリート",
      localeSwitching: "ページリロードなしのロケール切り替え",
      generateLocales: "AIまたはローカルOllamaでロケールを生成",
    },
    description:
      "一度設定すれば、どこでも翻訳できる。Next.js、Astro、React、TanStack Router、あらゆるTypeScript環境に対応した型安全なi18n。",
    primaryCta: "ドキュメントを見る",
    secondaryCta: "GitHubで見る",
    sponsorCta: "プロジェクトをスポンサーする",
    title: "あらゆるTypeScriptプロジェクト向けの1つのi18n設定",
  },
  thanksForSupport: {
    title: "ご支援ありがとうございます！",
    description:
      "あなたのスポンサーシップは大きな意味があります。better-translateをオープンソースで維持し、メンテナンスし、誰にでも無料で提供し続けるのに役立ちます。",
    impact1: "継続的な開発とメンテナンスを可能にします",
    impact2: "ライブラリを無料かつオープンソースに保ちます",
    impact3: "新しいフレームワークアダプターと機能の開発資金を提供します",
    backHome: "ホームに戻る",
    viewGithub: "GitHubで見る",
  },
  docs: {
    copyMarkdown: "マークダウンをコピー",
    copiedMarkdown: "コピーしました",
    header: {
      home: "ホーム",
      github: "GitHub",
    },
    sidebar: {
      rtl: "RTL",
      adapters: "アダプター",
      astro: "Astro",
      changelog: "変更履歴",
      cli: "CLI",
      core: "コア",
      expo: "Expo",
      gettingStarted: "はじめる",
      installation: "インストール",
      introduction: "はじめに",
      mission: "ミッション",
      mdAndMdx: "MD & MDX",
      nextjs: "Next.js",
      react: "React",
      skills: "スキル",
      tanstackStart: "TanStack Router",
    },
  },
} as const;

export default ja;
